[2022-12-08T22:30:49.838+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:28:19.960165+00:00 [queued]>
[2022-12-08T22:30:49.854+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:28:19.960165+00:00 [queued]>
[2022-12-08T22:30:49.855+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T22:30:49.857+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2022-12-08T22:30:49.858+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T22:30:49.879+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): First_task_backup> on 2022-12-08 22:28:19.960165+00:00
[2022-12-08T22:30:49.887+0000] {standard_task_runner.py:55} INFO - Started process 6147 to run task
[2022-12-08T22:30:49.894+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'back_in_avro', 'First_task_backup', 'manual__2022-12-08T22:28:19.960165+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_back_in_avro.py', '--cfg-path', '/tmp/tmpjcpyzorc']
[2022-12-08T22:30:49.898+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask First_task_backup
[2022-12-08T22:30:50.018+0000] {task_command.py:389} INFO - Running <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:28:19.960165+00:00 [running]> on host c4fdd5f7672d
[2022-12-08T22:30:50.216+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Martin_Jurado
AIRFLOW_CTX_DAG_ID=back_in_avro
AIRFLOW_CTX_TASK_ID=First_task_backup
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T22:28:19.960165+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-08T22:28:19.960165+00:00
[2022-12-08T22:30:50.306+0000] {logging_mixin.py:137} INFO - There is information in the database
[2022-12-08T22:30:50.356+0000] {logging_mixin.py:137} INFO - Error to write the file
[2022-12-08T22:30:50.359+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-08T22:30:50.376+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=back_in_avro, task_id=First_task_backup, execution_date=20221208T222819, start_date=20221208T223049, end_date=20221208T223050
[2022-12-08T22:30:50.432+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-08T22:30:50.459+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
